export interface Source {
      id: string;
      type: 'pdf' | 'audio' | 'image' | 'website' | 'youtube' | 'copiedText';
      title: string;
      content: string; // The raw text extracted
      createdAt: number;
      metadata?: Record<string, any>;
    }

    export interface Note {
      id: string;
      content: string;
      createdAt: number;
    }

    export interface Artifact {
      id: string;
      type: 'flashcards' | 'quiz' | 'infographic' | 'slideDeck' | 'audioOverview' | 'knowledgeGraph';
      title: string;
      content: any; // Structured JSON or text
      createdAt: number;
      status: 'generating' | 'completed' | 'failed';
    }

/**
 * A flashcard consists of a prompt on the front and the answer on the back.
 * Flashcards are typically generated by the AI from the user's sources to
 * facilitate active recall.  They can be displayed one at a time, with the
 * user flipping to reveal the answer.
 */
export interface Flashcard {
  id: string;
  question: string;
  answer: string;
}

/**
 * A quiz question may be multiple choice or free-form.  For simplicity
 * multiple choice questions include a list of possible answers with the
 * index of the correct choice.  Free-form questions omit the choices and
 * instead rely on the answer field for evaluation.
 */
export interface QuizQuestion {
  id: string;
  prompt: string;
  options?: string[];
  correctIndex?: number;
  answer?: string;
}

    export interface Notebook {
      id: string;
      title: string;
      description: string;
      sources: Source[];
      artifacts: Artifact[];
      createdAt: number;
      updatedAt: number;
    }

    export interface ChatMessage {
      id: string;
      role: 'user' | 'model';
      text: string;
      isStreaming?: boolean;
      citations?: string[];
      groundingMetadata?: any; // Google Search Grounding Data
    }

    export interface Notification {
      id: string;
      title: string;
      message: string;
      type: 'success' | 'error' | 'info';
    }

    export interface BackgroundJob {
      id: string;
      notebookId: string;
      type: Artifact['type'];
      status: 'pending' | 'processing' | 'completed' | 'failed';
      progress?: string;
    }